AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

RSpec/RepeatedExampleGroupBody:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/GuardClause:
  Enabled: false

require:
  - rubocop-rspec
  - rubocop-rake
