name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.92.0
        with:
          ruby-version: 3.0
      - name: Install dependencies
        run: bundle install
      - name: Run rake
        run: bundle exec rake
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0